### PR TITLE
[LABX-9] Add UserManager and tests

### PR DESCRIPTION
**Pull request by soleth**
Add conversion helpers to StorageInterface.
Make StorageInterface return success on set.
Add EventsHistory.

### CODE REVIEW

**Comment by lastperson** [comment]
Will recreate from main account.

**Comment by lastperson** [comment]
@Polycarpik please review.

**Comment by Mikefluff** [comment]
Didn’t find any UserLibrary. All business logic should be holded in libraries, not in contracts!

**Comment by lastperson** [comment]
@Polycarpik check this out.
@Mikefluff can you please create a JIRA task to investigate/create delegatecall wrapper, so that we can adopt it later, and split UserLibrary into library and manager?

**Comment by lastperson** [comment]
@Polycarpik review.

**Pull request merged**
